name: Build project

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: |
          sudo apt-get -qq update
          sudo apt-get upgrade
          sudo apt-get -y install cmake libhidapi-dev libsamplerate0-dev libminizip-dev libsdl2-dev libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev pkg-config zlib1g-dev binutils-dev libspeexdsp-dev qt5-default build-essential nasm git zip
      - name: Build RMG
        run: bash ./Source/Script/Build.sh Release
      - name: Package RMG
        run: bash ./Source/Script/Package.sh Release
      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: Linux Build
          path: Bin/*.zip

  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-hidapi
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-jasper
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-hidapi
            mingw-w64-x86_64-libsamplerate
            mingw-w64-x86_64-python3-pip
            mingw-w64-x86_64-python3-pyopenssl
            mingw-w64-x86_64-nasm
            git
      - name: Build RMG
        run: msys2 -c './Source/Script/Build.sh Release'
      - name: Create Setup
        run: .\Build\Release\Source\Installer\CreateInstaller.bat
      - name: Upload Setup
        uses: actions/upload-artifact@v2
        with:
          name: Windows Build
          path: Bin/*.exe